env:
  - DJANGO=3.0
  - DJANGO=3.2.7
language: python
python:
  - "3.7"
  - "3.8"
  - "3.9"

install:
  - pip install django==${DJANGO}
  - pip install .

script:
  - python test_project/manage.py test resigner_tests
