language: python

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"

env:
  - DJANGO_VERSION=1.4
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10

matrix:
  allow_failures:
    - env: DJANGO_VERSION=1.4

install:
  - pip install django==${DJANGO_VERSION}
  - pip install .

script:
  - python test_project/manage.py test resigner_tests
