language: python

python:
  - "2.7"
  - "3.6"

env:
  - DJANGO_VERSION=1.7
  - DJANGO_VERSION=1.8
  - DJANGO_VERSION=1.9
  - DJANGO_VERSION=1.10.5

matrix:
  allow_failures:
    - env: DJANGO_VERSION=1.7
      python: "3.6"

install:
  - pip install django==${DJANGO_VERSION}
  - pip install .

script:
  - python test_project/manage.py test resigner_tests
