env:
  - DJANGO=2.2
  - DJANGO=3.0
language: python
python:
  - "3.7"
  - "3.8"

install:
  - pip install django==${DJANGO}
  - pip install .

script:
  - python test_project/manage.py test resigner_tests
