env:
  - DJANGO=2.0
  - DJANGO=2.1
  - DJANGO=2.2
language: python
python:
  - "3.6"
  - "3.7"

install:
  - pip install django==${DJANGO}
  - pip install .

script:
  - python test_project/manage.py test resigner_tests
