env:
  matrix:
    - DJANGO=2.0
    - DJANGO=2.1.8
language: python
python:
  - "3.6"

install:
  - pip install django==${DJANGO}
  - pip install .

script:
  - python test_project/manage.py test resigner_tests
